/* Synth patches. `send` values seed the reverb/delay macros when a patch is
   loaded, the way a hardware preset recalls its effect levels. */

export const PRESETS = [
  {
    id: 'warm-keys',
    name: 'Warm Keys',
    category: 'Keys',
    color: '#f0a860',
    blurb: 'Rounded electric piano. The safe default.',
    gain: 0.19,
    oscs: [
      { type: 'sawtooth', semi: 0, cents: -4, level: 0.7 },
      { type: 'triangle', semi: 0, cents: 5, level: 0.6 },
    ],
    sub: { type: 'sine', level: 0.28, octave: -1 },
    noise: 0,
    filter: { type: 'lowpass', hz: 1500, q: 1.2, env: 2200, keytrack: 0.35, envA: 0.004, envD: 0.5, envS: 0.35, envR: 0.4 },
    amp: { a: 0.006, d: 0.45, s: 0.5, r: 0.45 },
    lfo: { type: 'sine', rate: 5, target: 'pitch', amount: 0, delay: 0 },
    unison: { voices: 1, spread: 0 },
    vel: { amp: 0.8, filter: 0.6 },
    send: { reverb: 0.26, delay: 0.08 },
    macroCutoff: 0.74,
    panSpread: 0.15,
  },
  {
    id: 'glass-bells',
    name: 'Glass Bells',
    category: 'Bells',
    color: '#63d7e8',
    blurb: 'FM bell that rings out. Toddler-proof — always pretty.',
    gain: 0.17,
    oscs: [{ type: 'sine', semi: 0, cents: 0, level: 1 }],
    sub: { type: 'sine', level: 0, octave: -1 },
    noise: 0,
    fm: { type: 'sine', ratio: 3.01, index: 820, decay: 0.55 },
    filter: { type: 'lowpass', hz: 6500, q: 0.7, env: 0, keytrack: 0.2, envA: 0.001, envD: 0.2, envS: 1, envR: 0.2 },
    amp: { a: 0.002, d: 1.7, s: 0, r: 0.7 },
    vel: { amp: 0.7, filter: 0 },
    chorus: 0.22,
    send: { reverb: 0.45, delay: 0.18 },
    macroCutoff: 0.85,
    panSpread: 0.3,
  },
  {
    id: 'velvet-pad',
    name: 'Velvet Pad',
    category: 'Pads',
    color: '#a98cf0',
    blurb: 'Slow swell, wide and lush. Hold a chord and float.',
    gain: 0.13,
    oscs: [
      { type: 'sawtooth', semi: 0, cents: -8, level: 0.55 },
      { type: 'sawtooth', semi: 0, cents: 9, level: 0.55 },
      { type: 'triangle', semi: 12, cents: 0, level: 0.25 },
    ],
    sub: { type: 'sine', level: 0.22, octave: -1 },
    noise: 0.015,
    filter: { type: 'lowpass', hz: 850, q: 2.4, env: 1400, keytrack: 0.25, envA: 0.6, envD: 1.4, envS: 0.6, envR: 1.2 },
    amp: { a: 0.55, d: 1.2, s: 0.75, r: 1.7 },
    lfo: { type: 'sine', rate: 0.28, target: 'filter', amount: 0.22, delay: 1.2 },
    unison: { voices: 3, spread: 13 },
    vel: { amp: 0.45, filter: 0.4 },
    chorus: 0.55,
    send: { reverb: 0.6, delay: 0.2 },
    macroCutoff: 0.66,
    panSpread: 0.5,
  },
  {
    id: 'rubber-bass',
    name: 'Rubber Bass',
    category: 'Bass',
    color: '#f06a7a',
    blurb: 'Mono, squelchy, with glide. Play it low.',
    gain: 0.26,
    mono: true,
    glide: 0.055,
    oscs: [
      { type: 'sawtooth', semi: 0, cents: 0, level: 0.8 },
      { type: 'square', semi: 0, cents: -6, level: 0.4 },
    ],
    sub: { type: 'sine', level: 0.5, octave: -1 },
    noise: 0,
    filter: { type: 'lowpass', hz: 420, q: 7, env: 2400, keytrack: 0.4, envA: 0.004, envD: 0.22, envS: 0.15, envR: 0.15 },
    amp: { a: 0.004, d: 0.2, s: 0.42, r: 0.16 },
    vel: { amp: 0.6, filter: 0.8 },
    send: { reverb: 0.06, delay: 0.04 },
    macroCutoff: 0.6,
    panSpread: 0,
  },
  {
    id: 'music-box',
    name: 'Music Box',
    category: 'Bells',
    color: '#ffd166',
    blurb: 'Plinky and sweet. A favourite with small hands.',
    gain: 0.2,
    oscs: [
      { type: 'triangle', semi: 0, cents: 0, level: 0.9 },
      { type: 'sine', semi: 12, cents: 3, level: 0.35 },
      { type: 'sine', semi: 19, cents: 0, level: 0.12 },
    ],
    sub: { type: 'sine', level: 0, octave: -1 },
    noise: 0,
    filter: { type: 'lowpass', hz: 4200, q: 0.9, env: 1800, keytrack: 0.5, envA: 0.001, envD: 0.35, envS: 0.2, envR: 0.2 },
    amp: { a: 0.001, d: 0.95, s: 0, r: 0.5 },
    vel: { amp: 0.75, filter: 0.3 },
    chorus: 0.2,
    send: { reverb: 0.4, delay: 0.12 },
    macroCutoff: 0.82,
    panSpread: 0.25,
  },
  {
    id: 'marimba',
    name: 'Marimba',
    category: 'Percussive',
    color: '#e8a05c',
    blurb: 'Woody mallet tone. Percussive and forgiving.',
    gain: 0.24,
    oscs: [
      { type: 'sine', semi: 0, cents: 0, level: 1 },
      { type: 'sine', semi: 24, cents: 4, level: 0.22 },
      { type: 'triangle', semi: 12, cents: 0, level: 0.14 },
    ],
    sub: { type: 'sine', level: 0, octave: -1 },
    noise: 0,
    filter: { type: 'lowpass', hz: 3200, q: 1, env: 1200, keytrack: 0.6, envA: 0.001, envD: 0.18, envS: 0.1, envR: 0.15 },
    amp: { a: 0.002, d: 0.55, s: 0, r: 0.3 },
    vel: { amp: 0.8, filter: 0.5 },
    send: { reverb: 0.28, delay: 0.06 },
    macroCutoff: 0.78,
    panSpread: 0.35,
  },
  {
    id: 'supersaw',
    name: 'Supersaw Lead',
    category: 'Lead',
    color: '#6ee7a0',
    blurb: 'Big detuned stack. Turn the delay up.',
    gain: 0.12,
    oscs: [
      { type: 'sawtooth', semi: 0, cents: 0, level: 0.7 },
      { type: 'sawtooth', semi: 0, cents: 12, level: 0.6 },
      { type: 'sawtooth', semi: -12, cents: -6, level: 0.3 },
    ],
    sub: { type: 'sine', level: 0.15, octave: -1 },
    noise: 0,
    filter: { type: 'lowpass', hz: 2600, q: 2, env: 4200, keytrack: 0.3, envA: 0.01, envD: 0.4, envS: 0.5, envR: 0.35 },
    amp: { a: 0.012, d: 0.3, s: 0.72, r: 0.32 },
    lfo: { type: 'sine', rate: 5.4, target: 'pitch', amount: 0.12, delay: 0.5 },
    unison: { voices: 3, spread: 20 },
    vel: { amp: 0.7, filter: 0.6 },
    chorus: 0.35,
    send: { reverb: 0.3, delay: 0.3 },
    macroCutoff: 0.76,
    panSpread: 0.55,
  },
  {
    id: 'drawbar-organ',
    name: 'Drawbar Organ',
    category: 'Keys',
    color: '#f2854f',
    blurb: 'Additive sines, instant on and off.',
    gain: 0.14,
    oscs: [
      { type: 'sine', semi: 0, cents: 0, level: 1 },
      { type: 'sine', semi: 12, cents: 0, level: 0.55 },
      { type: 'sine', semi: 19, cents: 0, level: 0.3 },
      { type: 'sine', semi: 24, cents: 0, level: 0.2 },
    ],
    sub: { type: 'sine', level: 0.2, octave: -1 },
    noise: 0,
    filter: { type: 'lowpass', hz: 5200, q: 0.6, env: 0, keytrack: 0.3, envA: 0.001, envD: 0.1, envS: 1, envR: 0.1 },
    amp: { a: 0.008, d: 0.05, s: 0.95, r: 0.08 },
    lfo: { type: 'sine', rate: 6.2, target: 'pitch', amount: 0.09, delay: 0.2 },
    vel: { amp: 0.35, filter: 0.2 },
    send: { reverb: 0.22, delay: 0.05 },
    macroCutoff: 0.8,
    panSpread: 0.1,
  },
  {
    id: 'dream-choir',
    name: 'Dream Choir',
    category: 'Pads',
    color: '#8fb8ff',
    blurb: 'Breathy and distant. Very calming.',
    gain: 0.13,
    oscs: [
      { type: 'triangle', semi: 0, cents: -5, level: 0.7 },
      { type: 'sawtooth', semi: 0, cents: 7, level: 0.3 },
      { type: 'triangle', semi: 12, cents: 0, level: 0.2 },
    ],
    sub: { type: 'sine', level: 0.12, octave: -1 },
    noise: 0.03,
    filter: { type: 'lowpass', hz: 1150, q: 3.2, env: 900, keytrack: 0.3, envA: 0.45, envD: 1.1, envS: 0.55, envR: 1 },
    amp: { a: 0.4, d: 0.9, s: 0.8, r: 1.5 },
    lfo: { type: 'sine', rate: 4.6, target: 'pitch', amount: 0.16, delay: 0.8 },
    unison: { voices: 2, spread: 9 },
    vel: { amp: 0.4, filter: 0.35 },
    chorus: 0.5,
    send: { reverb: 0.72, delay: 0.16 },
    macroCutoff: 0.7,
    panSpread: 0.6,
  },
  {
    id: 'toy-piano',
    name: 'Toy Piano',
    category: 'Percussive',
    color: '#ff8fb1',
    blurb: 'Tin-can charm, short and cheerful.',
    gain: 0.2,
    oscs: [
      { type: 'square', semi: 0, cents: 0, level: 0.45 },
      { type: 'triangle', semi: 12, cents: 8, level: 0.6 },
      { type: 'sine', semi: 28, cents: 0, level: 0.1 },
    ],
    sub: { type: 'sine', level: 0, octave: -1 },
    noise: 0.02,
    filter: { type: 'bandpass', hz: 1900, q: 1.4, env: 2600, keytrack: 0.7, envA: 0.001, envD: 0.12, envS: 0.15, envR: 0.12 },
    amp: { a: 0.001, d: 0.4, s: 0, r: 0.22 },
    vel: { amp: 0.85, filter: 0.5 },
    send: { reverb: 0.3, delay: 0.1 },
    macroCutoff: 0.8,
    panSpread: 0.2,
  },
  {
    id: 'wobble-bass',
    name: 'Wobble Bass',
    category: 'Bass',
    color: '#c3f53c',
    blurb: 'LFO on the filter. Silly in the best way.',
    gain: 0.24,
    mono: true,
    glide: 0.03,
    oscs: [
      { type: 'sawtooth', semi: 0, cents: 0, level: 0.85 },
      { type: 'square', semi: -12, cents: 0, level: 0.35 },
    ],
    sub: { type: 'sine', level: 0.45, octave: -1 },
    noise: 0,
    filter: { type: 'lowpass', hz: 500, q: 9, env: 1200, keytrack: 0.2, envA: 0.01, envD: 0.3, envS: 0.4, envR: 0.2 },
    amp: { a: 0.008, d: 0.2, s: 0.7, r: 0.2 },
    lfo: { type: 'sine', rate: 4.2, target: 'filter', amount: 0.75, delay: 0 },
    vel: { amp: 0.5, filter: 0.6 },
    send: { reverb: 0.08, delay: 0.1 },
    macroCutoff: 0.55,
    panSpread: 0,
  },
  {
    id: 'cosmic-pluck',
    name: 'Cosmic Pluck',
    category: 'Lead',
    color: '#7cf2d8',
    blurb: 'Short pluck drenched in delay. Great with the arp.',
    gain: 0.19,
    oscs: [
      { type: 'sawtooth', semi: 0, cents: -3, level: 0.7 },
      { type: 'square', semi: 7, cents: 4, level: 0.25 },
    ],
    sub: { type: 'sine', level: 0.18, octave: -1 },
    noise: 0,
    filter: { type: 'lowpass', hz: 900, q: 6, env: 6000, keytrack: 0.4, envA: 0.001, envD: 0.16, envS: 0.05, envR: 0.15 },
    amp: { a: 0.002, d: 0.3, s: 0.08, r: 0.3 },
    vel: { amp: 0.8, filter: 0.75 },
    chorus: 0.28,
    send: { reverb: 0.35, delay: 0.42 },
    macroCutoff: 0.72,
    panSpread: 0.4,
  },
];

const BY_ID = new Map(PRESETS.map((p) => [p.id, p]));

export function getPreset(id) {
  return BY_ID.get(id) || PRESETS[0];
}

export const PRESET_CATEGORIES = [...new Set(PRESETS.map((p) => p.category))];

/** Patches offered in Bash mode, in the order they appear on the big buttons. */
export const BASH_SOUNDS = [
  { id: 'bells', label: 'Bells', presetId: 'glass-bells', emoji: '🔔' },
  { id: 'marimba', label: 'Marimba', presetId: 'marimba', emoji: '🪵' },
  { id: 'musicbox', label: 'Music box', presetId: 'music-box', emoji: '🎁' },
  { id: 'space', label: 'Space', presetId: 'dream-choir', emoji: '🚀' },
  { id: 'piano', label: 'Toy piano', presetId: 'toy-piano', emoji: '🎹' },
  { id: 'organ', label: 'Organ', presetId: 'drawbar-organ', emoji: '🎪' },
];
